version: "3.9"
services:
    # database container
    postgres-container:
        image: postgres:17-alpine
        restart: always
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DB}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DB}"]
            interval: 5s
            timeout: 5s
            retries: 5
volumes:
    postgres-data:
        driver: local
